name: ConnectPlugin
version: '${version}'
main: dev.silal.connectplugin.ConnectPlugin
api-version: '1.17'
website: https://conbot.xyz
description: Connect Minecraft and Discord
authors: [Silal]

softdepend: [PlaceholderAPI]

commands:
  link:
    description: Link with discord
    aliases: [clink, dclink]
  unlink:
    description: Unlink with discord
    aliases: [cunlink, dcunlink]
  data:
    description: Get/Set the data
    aliases: [cdata, connectdata]
  bot:
    description: Get the bot invite
    aliases: [cbot]
  connectplugin:
    description: Setup command
    aliases: [cp, conpl]

permissions:
  connect.data.set:
    default: op
  connect.data.get:
    default: op
  connect.server.setup:
    default: op